<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TermSquared.Core\TermSquared.Core.csproj" />
    <ProjectReference Include="..\TermSquared.Mcp\TermSquared.Mcp.csproj" />
    <ProjectReference Include="..\TermSquared.Security\TermSquared.Security.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>
</Project>
