name: ci

on:
  push:
  pull_request:

jobs:
  windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
      - run: dotnet restore TermSquared.slnx
      - run: dotnet build TermSquared.slnx --configuration Release --no-restore
      - run: dotnet test TermSquared.slnx --configuration Release --no-build
